CASMCMS-7676 Enable loading of recipes with template-dicts
Cray-HPE/ims-load-artifacts pull request #11
Opened 2022-02-08 21:46 UTC by ecozzi-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

This PR updates ims-load-artifacts to be able to add recipes to IMS that contain template-dictionaries. 

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

yes

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMCMS-7676](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7676)

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [ ] Target branch correct
- [x] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-02-09 21:32 UTC, ecozzi-hpe commented
Builds will fail until the version of IMS-python-helper is updated.

2022-02-14 22:11 UTC, jsollom-hpe approved these changes

2022-02-14 22:11 UTC, jsollom-hpe commented on ims_load_artifacts/load_artifacts.py
> +                f"Cannot process manifest.yaml due to unsupported or missing manifest version {manifest_data}") \
Did you want to output the entire manifest_data here or just manifest_data["version"]?

2022-02-14 22:23 UTC, ecozzi-hpe commented on constraints.txt
> +ims-python-helper==0.4.68
This PR requires a new version of ims-python-helper. But, that version of ims-python-helper is also not yet released/merged. In order to test, I was forced to pin the version of ims-python-helper to this development version. Once ims-python-helper is merged to master and released, the version in this constraints file will need to be updated.

2022-02-16 19:21 UTC, ecozzi-hpe commented on constraints.txt
> +ims-python-helper==0.4.68
- [ ] Pin ims-python-helper to release version

2022-02-16 19:25 UTC, ecozzi-hpe commented on ims_load_artifacts/load_artifacts.py
> +                f"Cannot process manifest.yaml due to unsupported or missing manifest version {manifest_data}") \
The entire manifest data. The version could either blank or an unsupported version. Reporting the whole manifest gives the most information and allows the user to understand the error.

2022-02-17 16:37 UTC, rkleinman-hpe requested changes

2022-02-17 16:37 UTC, rkleinman-hpe commented on ims_load_artifacts/load_artifacts.py
> +                return ih.recipe_upload(recipe_name, recipe_path, linux_distribution, template_dictionary)
I believe this also means this change is backwards incompatible, requiring a major version rev.

2022-02-17 17:18 UTC, ecozzi-hpe commented on ims_load_artifacts/load_artifacts.py
> +                return ih.recipe_upload(recipe_name, recipe_path, linux_distribution, template_dictionary)
I don't know that I agree. The `template_dictionary` value is defaulted it if it is not found in the recipe_data. The version of ims-python-helper is pinned to support this parameter being passed. Not sure how this is a breaking change.

2022-02-17 18:55 UTC, rkleinman-hpe commented on ims_load_artifacts/load_artifacts.py
> +                return ih.recipe_upload(recipe_name, recipe_path, linux_distribution, template_dictionary)
Now that the ims python helper is backwards compatible, I agree.

2022-05-13 00:11 UTC, mharding-hpe approved these changes

2022-05-27 18:19 UTC, closed without merging