CASM-3506: Add IUF support
Cray-HPE/ims-load-artifacts pull request #29
Opened 2022-11-15 23:29 UTC by jack-stanek-hpe

## Summary and Scope
This change adds support for the IUF in the `load-ims-artifacts` image in order to implement the ims-upload operation. It requires that the IUF release distribution be mounted within the container, and that the `IUF` and `IUF_RELEASE_PATH` environment variables be set. Other environment variables must be set within the container as normal.

Existing `load-ims-artifacts` images should still be compatible with this change. Additionally, `manifest.yaml` files from existing `load-ims-artifacts` images can be used with the IUF ims-upload operation, maintaining backwards compatibility.

## Issues and Related PRs

* Resolves [CRAYSAT-3506](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3506)

## Testing

### Tested on:

  * `frigg`, `mug`
  * Local development environment

### Test description:

Run IUF workflows using enumerated IUF manifests and existing content directories. Ensure that content is uploaded as expected.

## Risks and Mitigations

Does not affect existing implementation.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-11-29 20:41 UTC, haasken-hpe approved these changes
Mostly minor comments.

2022-11-29 20:41 UTC, haasken-hpe commented on ims_load_artifacts/load_artifacts.py
>      # pylint: disable=global-statement
Should be able to get rid of this now.

2022-11-29 20:41 UTC, haasken-hpe commented on ims_load_artifacts/loaders.py
> +class ImsLoadArtifacts_v1_0_0:
It looks like the only significant difference I'm seeing between the old version of this class and the new one is the name had its leading underscore removed, and the addition of reading a token from the `AUTH_TOKEN` environment variable if it's set. Is there anything else to be aware of here?

2022-11-29 20:41 UTC, haasken-hpe commented on tests/test_iuf.py
> +
PEP 8 wants another blank line here.

2022-11-29 20:41 UTC, haasken-hpe commented on tests/test_iuf.py
> +def enumerated_manifest():
IMO, it would help to put "IUF" in the name of this fixture somehow. E.g., `enumerated_iuf_manifest`. Otherwise it's easy to confuse with the ims-load-artifacts manifest like the one above in `content_dir_manifest`.

2022-11-29 20:41 UTC, haasken-hpe commented on tests/test_iuf.py
> +def mixed_manifest():
Suggest naming this `mixed_iuf_manifest` to be clear that this is the IUF Product Manifest.

2022-11-29 20:41 UTC, haasken-hpe commented on tests/test_iuf.py
> +
PEP 8 wants to remove two blank lines here.

2022-11-29 21:07 UTC, jack-stanek-hpe commented on constraints.txt
> +ims-python-helper==2.9.0
I changed this since it's a `constraints.txt` file, so that the versions stay pinned in case there's a new published version (especially a new major version since `>=` doesn't prevent that.)

2022-11-29 21:10 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +            recipe_name = os.path.basename(recipe_path).split('.')[0]
That's a fair point, though I think it's also possible for the recipe to end in `.tgz` as well. Might be worth to check if the extension is `".tar.gz"`, and otherwise just strip the extension?

2022-11-29 21:14 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +        processed_recipes[recipe_name] = built_recipe
Yeah, I'll add a warning log message in this instance if there's a duplicate key. I can add a note to the IUF manifest about it too.

2022-11-29 21:19 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +                'path': recipe['path']
Yes, I think that's right, though it should still work since `distribution_root` is the working directory of the container. I'll change it to be consistent and maybe a little more robust.

2022-11-29 21:25 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +            processed_images[image.get('name', image['path'])] = {
That seems good. Another thing to consider is if the basename of some image's path is the same as the specified name in the IUF product manifest, there will be a collision when there doesn't necessarily need to be one. This is getting me thinking about how we should handle duplicates in the IUF manifest should be handled; we may not need to actually discard every duplicated instance except the last, other options could be giving each duplicate a unique suffix, e.g. an increasing counter or something like that. Such a solution could make it complicated to figure out which image in the IUF manifest (or content dir manifests) a given IMS image corresponds to.

2022-11-29 21:33 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +    Note that this function has a side effect of mutating the content_dir_manifest
Ah, good catch. This comment is out of date.

2022-11-29 21:55 UTC, jack-stanek-hpe commented on ims_load_artifacts/loaders.py
> +class ImsLoadArtifacts_v1_0_0:
That's correct. I didn't make any other changes to the implementation, though there may be some differences with other relative import paths as I used the PyCharm refactor tool to move this class, and that can change import paths sometimes.

2022-11-29 21:57 UTC, jack-stanek-hpe commented on tests/test_iuf.py
> +def enumerated_manifest():
That's a good call, just to remove some ambiguity.

2022-11-29 22:01 UTC, jack-stanek-hpe commented on ims_load_artifacts/load_artifacts.py
>          #   secret_key: NDdHZUdPanhPNlhRc2RMUWxyb1k3WXhvMWNqb2NLMmoxQnBRb0o4NQ==
Yeah, though it doesn't really matter if I delete it -- it's still in the git history and has been for a while. While I doubt it's a real secret key from a running system at this point, to get rid of it we'd need to use something like `git-filter-repo`.

2022-11-29 22:53 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +            new_manifest['images'][image_name]['artifacts'][idx]['link']['path'] = fix_path(old_path)
Ah yeah, that should work. I was being overly cautious trying to explicitly mutate the nested dicts, but this is much cleaner.

2022-11-30 20:37 UTC, haasken-hpe requested changes
Found a minor bug with `rstrip` usage

2022-11-30 21:09 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +                recipe_name = recipe_basename.rstrip('.tar.gz')
Nice catch. I think we're in luck though, as we can use [`str.removesuffix`](https://docs.python.org/3/library/stdtypes.html#str.removesuffix) since the base Alpine image has Python 3.9:
```
$ docker run --rm artifactory.algol60.net/docker.io/alpine:3.15 /bin/sh -c 'apk add python3 && python3 --version'
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/13) Installing libbz2 (1.0.8-r1)
(2/13) Installing expat (2.5.0-r0)
(3/13) Installing libffi (3.4.2-r1)
(4/13) Installing gdbm (1.22-r0)
(5/13) Installing xz-libs (5.2.5-r1)
(6/13) Installing libgcc (10.3.1_git20211027-r0)
(7/13) Installing libstdc++ (10.3.1_git20211027-r0)
(8/13) Installing mpdecimal (2.5.1-r1)
(9/13) Installing ncurses-terminfo-base (6.3_p20211120-r1)
(10/13) Installing ncurses-libs (6.3_p20211120-r1)
(11/13) Installing readline (8.1.1-r0)
(12/13) Installing sqlite-libs (3.36.0-r0)
(13/13) Installing python3 (3.9.15-r0)
Executing busybox-1.34.1-r7.trigger
OK: 56 MiB in 27 packages
Python 3.9.15
```

2022-11-30 21:26 UTC, haasken-hpe commented on ims_load_artifacts/iuf.py
> +                recipe_name = recipe_basename.rstrip('.tar.gz')
Nice!

2022-11-30 22:58 UTC, haasken-hpe approved these changes

2022-12-06 15:34 UTC, jsollom-hpe approved these changes

2022-12-07 21:05 UTC, jack-stanek-hpe commented on ims_load_artifacts/iuf.py
> +    rewrites the file paths so the filesystem root is interpreted as
I reworded the sentence to change "so" to "such that".

2022-12-08 22:05 UTC, merged